gen: gen_trace gen_trace_transactionless gen_data_file gen_output check_results gen_output_transactionless 

gen_trace: gen_trace.cpp
	g++ -o gen_trace gen_trace.cpp

gen_data_file: gen_data_file.cpp
	g++ -o gen_data_file gen_data_file.cpp

gen_output: gen_output.cpp
	g++ -o gen_output gen_output.cpp




gen_output_transactionless: gen_output_transactionless.cpp
	g++ -o gen_output_transactionless gen_output_transactionless.cpp

gen_trace_transactionless: gen_trace_transactionless.cpp
	g++ -o gen_trace_transactionless gen_trace_transactionless.cpp
